### ISSUE TITLE
Blender 3.0 import error (Solution included)

### ISSUE THREAD

**Issue by NovaliX-Dev** [gregzaal/Gaffer#133] opened 2021-12-03 21:42 UTC
When i attempt to activate Gaffer (installed), i obtain this error:

### with default name ("Gaffer-3.1.9.zip")
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'

### with altered name ("Gaffer-3.1.9(1).zip")
Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 3.0\3.0\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3.1'

## Solution
1. Extract the folder
2. Rename the folder **inside** the folder created when extracted
3. Rename it to "Gaffer-3"
4. Zip and install **this folder** not the other

Renaming the folder to have only one extension("<name>.zip") seems to solve the problem for me.

_Seems to be a Blender bug in general, more precisely in his Python implementation, but i put this here, just in case someone has the same error has i have. The devs can fix the problem this way too._

**Comment by gregzaal** [comment] 2021-12-03 21:47
Duplicate of #112

**Closed by gregzaal** 2021-12-03 21:47 UTC
