### ISSUE TITLE
unsupport 3.1?

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [gregzaal/Gaffer#134] opened 2021-12-04 13:39 UTC
Traceback (most recent call last):
  File "G:\blender\blender3.0\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'

what's wrong

**Comment by ChildishGiant** [comment] 2021-12-04 13:49
Duplicate of #112

**Closed** 2021-12-14 09:18 UTC
