### ISSUE TITLE
Program can install, but cannot enable in user preferences

### ISSUE THREAD

**Issue by Lucien950** [gregzaal/Gaffer#116] opened 2020-07-06 15:41 UTC
![issue](https://user-images.githubusercontent.com/20777515/86612107-9d5a9d00-bf7d-11ea-85f4-73d5fcbcaefc.png)

**Comment by ChildishGiant** [comment] 2020-07-06 15:42
Probably a 2.83 bug from the looks of things

**Comment by gregzaal** [comment] 2020-07-06 15:49
Duplicate of #112

**Closed by gregzaal** 2020-07-06 15:49 UTC
