### ISSUE TITLE
Blender 3.6 Issue - I'm not able to install last version 3.1.17

### ISSUE THREAD

**Issue by Piergiorgio-PG** [gregzaal/Gaffer#158] opened 2023-06-30 08:42 UTC
***PLEASE NOTE***
If you did not purchase Gaffer, I cannot provide you any user support. This especially includes helping you install the add-on correctly. Check #112 (https://github.com/gregzaal/Gaffer/issues/112) if you are having installation problems.

----

**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to Preferences/Addon-ons/Install
2. Loaded Gaffer'
3. When I try to activate it I got 
5. Report: Error
* Traceback (most recent call last):
File "/Applications/Blender 3.6.app/Contents/Resources/3.6/scripts/modules/addon utils.py", line 333, in enable
mod = _ import_(module name)
ModuleNot FoundError: No module named 'Gaffer 3'

**Expected behaviour**

**Screenshots**

**System Information**
Operating system: macOS-13.4.1-arm64-arm-64bit 64 Bits
Graphics card: Metal API Apple M1 Max 1.2

**Blender Version**
Broken: version: 3.6.0, branch: blender-v3.6-release, commit date: 2023-06-27 08:08, hash: `c7fc78b81ecb`
Worked: (newest version of Blender that worked as expected)

Thank You!
PJ

**Comment by gregzaal** [comment] 2023-06-30 08:52
Duplicate of #112

**Closed by gregzaal** 2023-06-30 08:52 UTC
