### ISSUE TITLE
Can't install in blender 2.83 - No module named 'Gaffer-3'

### ISSUE THREAD

**Issue by ChildishGiant** [gregzaal/Gaffer#119] opened 2020-08-26 08:08 UTC
![image](https://user-images.githubusercontent.com/13716824/91277837-4736f880-e77b-11ea-820e-8d09737ae8fc.png)

```
Traceback (most recent call last):
  File "F:\steam\steamapps\common\Blender\2.83\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'
```

**Comment by gregzaal** [comment] 2020-08-26 08:22
Duplicate of #112

**Closed by gregzaal** 2020-08-26 08:22 UTC
