### ISSUE TITLE
Blender 2.79 (daily build 6859695) crashes when enabling Gaffer in the World panel

### ISSUE THREAD

**Issue by akej74** [gregzaal/Gaffer#83] opened 2017-09-08 18:55 UTC
Hi, did a test with Gaffer 3.0.2 in the latest build of blender 2.79 (daily build 6859695). Blender crashes immediately when you enable Gaffer in the World panel. I understand that this is not the official 2.79 release, but I would like to report this anyway, as it would be interesting to see the problem is related to Gaffer or some change/bug in Blender 2.79.

Second test was to run Blender from command line with "blender.exe -d". I can now enable Gaffer without any crashes and also generate thumbnail and render an image. Output on the console is:

Getting HDRI list from HDRI Haven...
    Can't fetch list from HDRI Haven

No errors were logged in the Gaffer log in ...\AppData\Roaming\Blender Foundation\Blender\data\gaffer

I hade a few HDRI's from HDRI Haven in the folder C:\HDRI as follows:

balcony_1k, 2k, 4k, 8k, 16k
cave_wall_1k, 2k, 4k, 8k, 16k

Please let me know if I can provide any more information, logs etc.

**Comment by gregzaal** [comment] 2017-09-08 19:40
Thanks for the report, can you copy paste the full console output here? Crashes can be caused by any number of things.

I suspect it might be related to a recent API change to do with the world panels, if so then it will only affect daily builds (and 2.8), the official 2.79 release won't be affected.

**Comment by akej74** [comment] 2017-09-08 21:03
Here follows the console output after enabling full debug. I performed the following steps:
* Go to world panel
* Enable HDRI checkbox (which works in debug mode)

`C:\Users\Ake>c:\Blender\blender-2.79.0-git.6859695-windows64\blender.exe --debug-all
Switching to fully guarded memory allocator.
read file C:\Users\Ake\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
  Version 279 sub 1 date 2017-09-04 19:04 hash 6859695
Read prefs: C:\Users\Ake\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
read file C:\Users\Ake\AppData\Roaming\Blender Foundation\Blender\2.79\config\startup.blend
  Version 279 sub 1 date 2017-09-04 19:04 hash 6859695

ordered
 OBCube
 OBLamp
 OBCamera
ED_screen_refresh: set screen
found bundled python: c:\Blender\blender-2.79.0-git.6859695-windows64\2.79\python
SRNA Subclassed: 'Context'
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'PropertyGroup'
SRNA Subclassed: 'Menu'
time bl_operators 0.0120
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Bone'
SRNA Subclassed: 'EditBone'
SRNA Subclassed: 'PoseBone'
SRNA Subclassed: 'UIList'
SRNA Subclassed: 'Mesh'
SRNA Subclassed: 'Object'
SRNA Subclassed: 'Texture'
SRNA Subclassed: 'Header'
time bl_ui 0.0296
SRNA Subclassed: 'KeyingSetInfo'
time keyingsets_builtins 0.0010
SRNA Subclassed: 'Node'
SRNA Subclassed: 'NodeInternal'
SRNA Subclassed: 'ShaderNode'
SRNA Subclassed: 'CompositorNode'
SRNA Subclassed: 'TextureNode'
time nodeitems_builtins 0.0035
SRNA Subclassed: 'WindowManager'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Operator'
        addon_utils.enable io_scene_3ds
SRNA Subclassed: 'Operator'
        addon_utils.enable io_scene_fbx
SRNA Subclassed: 'Operator'
        addon_utils.enable io_anim_bvh
SRNA Subclassed: 'Operator'
        addon_utils.enable io_mesh_ply
SRNA Subclassed: 'Operator'
        addon_utils.enable io_scene_obj
SRNA Subclassed: 'Operator'
        addon_utils.enable io_scene_x3d
SRNA Subclassed: 'Operator'
        addon_utils.enable io_mesh_stl
SRNA Subclassed: 'Operator'
        addon_utils.enable io_mesh_uv_layout
SRNA Subclassed: 'Operator'
        addon_utils.enable io_curve_svg
SRNA Subclassed: 'RenderEngine'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'PropertyGroup'
SRNA Subclassed: 'AddonPreferences'
I0908 23:00:12.006256  5176 blender_python.cpp:188] Debug flags initialized to:
CPU flags:
  AVX2   : True
  AVX    : True
  SSE4.1 : True
  SSE3   : True
  SSE2   : True
  QBVH   : True
  Split  : False
CUDA flags:
 Adaptive Compile: False
OpenCL flags:
  Device type    : ALL
  Kernel type    : DEFAULT
  Debug          : False
  Single program : True
  Memory limit   : zu
        addon_utils.enable cycles
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'PropertyGroup'
SRNA Subclassed: 'AddonPreferences'
        addon_utils.enable node_wrangler
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'Menu'
SRNA Subclassed: 'PropertyGroup'
        addon_utils.enable add_mesh_extra_objects
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'PropertyGroup'
        addon_utils.enable render_auto_tile_size
SRNA Subclassed: 'Operator'
SRNA Subclassed: 'Panel'
SRNA Subclassed: 'UIList'
SRNA Subclassed: 'AddonPreferences'
SRNA Subclassed: 'PropertyGroup'
        addon_utils.enable Gaffer-303
Python Script Load Time 0.1710
FRS_set_context: context 0x0000013757EB6C38 scene 0x0000013758948DB8
Thread 0: update object OBCamera
recalcob Camera
Thread 1: update object OBLamp
recalcob Lamp
Thread 0: update object OBCube
recalcob Cube
recalcdata Cube
Thread 0: total 2 objects in 0.000511 sec.
  Camera in 0.000173 sec
  Cube in 0.000338 sec
Thread 1: total 1 objects in 0.000146 sec.
  Lamp in 0.000146 sec
Thread 2: total 0 objects in 0.000000 sec.
Thread 3: total 0 objects in 0.000000 sec.
Thread 4: total 0 objects in 0.000000 sec.
Thread 5: total 0 objects in 0.000000 sec.
Thread 6: total 0 objects in 0.000000 sec.
Thread 7: total 0 objects in 0.000000 sec.
Scene updated 3 objects in 0.001074 sec
I0908 23:00:12.113040  5176 device_cuda.cpp:2092] CUEW initialization succeeded
I0908 23:00:12.113040  5176 device_cuda.cpp:2094] Found precompiled kernels
I0908 23:00:12.232858  5176 device_opencl.cpp:58] CLEW initialization succeeded.
I0908 23:00:12.242384  5176 opencl_util.cpp:778] Enumerating devices for platform NVIDIA CUDA.
I0908 23:00:12.242885  5176 opencl_util.cpp:842] Ignoring device GeForce GTX 1080, not officially supported yet.
ghost_event_proc: ghost redraw 1
ghost_event_proc: ghost redraw 1
ED_screen_refresh: set screen

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:1 / PRESS,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0,
         mouse:(2306,1136), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657F0128

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:2 / RELEASE,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0,
         mouse:(2306,1136), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657EF9A8

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:1 / PRESS,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0,
         mouse:(2185,807), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657EF6A8
DAG_id_tag_update_ex: id=WOWorld flag=0
SRNA Subclassed: 'NodeTree'
SRNA Subclassed: 'NodeSocketInterface'
Memoryblock free: pointer not in memlist
Memoryblock free: pointer not in memlist
Memoryblock free: pointer not in memlist
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
Memoryblock free: pointer not in memlist
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
Memoryblock free: pointer not in memlist
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
Memoryblock free: pointer not in memlist
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
Memoryblock free: pointer not in memlist
SRNA Subclassed: 'NodeSocket'
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTWarmth (Gaffer) flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=NTShader Nodetree flag=0
DAG_id_tag_update_ex: id=WOWorld flag=0
DAG_id_tag_update_ex: id=SCScene flag=7
read file
  Version 262 sub 3 date unknown hash
read file
  Version 268 sub 5 date unknown hash

wm_event_do_handlers: Handling event
wmEvent  type:1 / LEFTMOUSE, val:2 / RELEASE,
         shift:0, ctrl:0, alt:0, oskey:0, keymodifier:0,
         mouse:(2185,807), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657F07E8
ED_undo_push: Turn on/off Gaffer's HDRI handler
Job 'Icon Preview' finished in 0.104753 seconds
Job 'Icon Preview' finished in 0.097688 seconds
Job 'Icon Preview' finished in 0.097653 seconds
Job 'Icon Preview' finished in 0.103234 seconds

wm_event_do_handlers: Handling event
wmEvent  type:213 / LEFT_ALT, val:1 / PRESS,
         shift:0, ctrl:0, alt:1, oskey:0, keymodifier:0,
         mouse:(988,986), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657EFB28

wm_event_do_handlers: Handling event
wmEvent  type:260 / WINDOW_DEACTIVATE, val:1 / PRESS,
         shift:0, ctrl:0, alt:1, oskey:0, keymodifier:0,
         mouse:(988,986), ascii:' ', utf8:'', keymap_idname:(null), pointer:00000137657F10E8`

**Comment by akej74** [comment] 2017-09-08 21:07
I also run Blender from command line without debug as follows, it now crashed when enabling HDRI, but unfortunatly, no details in the output:

C:\Users\Ake>c:\Blender\blender-2.79.0-git.6859695-windows64\blender.exe
Read prefs: C:\Users\Ake\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: c:\Blender\blender-2.79.0-git.6859695-windows64\2.79\python

C:\Users\Ake>

**Comment by gregzaal** [comment] 2017-09-08 21:32
Interesting, a crash that bad with no error is likely a bug with blender itself. Afaik enabling debug mode doesn't change anything for add-ons, which further suggests it's a blender bug (which you can [report here](https://developer.blender.org/maniphest/task/edit/form/1)). Closing for now, but if nothing comes of your bug report there then we can re-open.

**Closed by gregzaal** 2017-09-08 21:32 UTC

**Comment by akej74** [comment] 2017-09-10 13:59
Update, tested the latest Blender build from September 10, problem is fixed, no more crash. So it was indeed a Blender issue.

**Comment by gregzaal** [comment] 2017-09-10 16:34
Great, thanks for the report anyway!
