### ISSUE TITLE
Image not set.

### ISSUE THREAD

**Issue by FuuChang** [gregzaal/Gaffer#91] opened 2018-08-08 15:26 UTC
When you select a thumbnail from the UI, a node is automatically created. There is no abnormality so far. However, the image of "environment texture" in the node is empty. How do I set it automatically?

The Blender you use is "2.79b", and the addon is using the latest.

**Comment by gregzaal** [comment] 2018-08-14 11:54
Sorry for the late response.

I can't reproduce this issue - can you provide more details? Are any errors printed in the [system console](https://i.imgur.com/VoXoIPF.png)? It may help to [upload your logs](https://i.imgur.com/Ps0qIKF.png).

**Comment by FuuChang** [comment] 2018-08-17 09:33
I'm glad just reply has arrived! Thank you!
The log could not be uploaded due to an error, write the log below.

We prepared a movie for which no image is set. I am glad if it becomes helpful.
Thank you.
[https://youtu.be/sYcq2e0-ins
](url)

----------------------------------------------------------
OpenColorIO Error: Error could not read 'D:\My Document\Cloud\Google Drive\PC Configuration　\Blender\Ver2.79b\2.79\datafiles\colormanagement\config.ocio' OCIO profile.
Color management: using fallback mode for management
Read prefs: C:\Users\Fu-Pi-\AppData\Roaming\Blender Foundation\Blender\2.79\config\userpref.blend
found bundled python: D:\My Document\Cloud\Google Drive\PC Configuration　\Blender\Ver2.79b\2.79\python
Registered Hard Ops 9 with 112 modules
Registered MESHmachine with 20 modules
Registered DECALmachine with 46 modules
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
RNA Warning: Current value "252" matches no enum in 'GafferProperties', '', 'hdri'
Traceback (most recent call last):
  File "C:\Users\Fu-Pi-\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Gaffer\functions.py", line 1040, in hdri_enable
    setup_hdri(self, context)
  File "C:\Users\Fu-Pi-\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Gaffer\functions.py", line 974, in setup_hdri
    set_image(context, os.path.join(prefs.hdri_path, gaf_props.hdri_variation), n_img)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xeb in position 1: invalid continuation byte
File "C:\Users\Fu-Pi-\AppData\Roaming\Blender Foundation\Blender\2.79\scripts\addons\Gaffer\functions.py", line 1002, in hdri_enable
----------------------------------------------------------

**Comment by FuuChang** [comment] 2018-08-17 09:35
It seems that the link above does not work.
Copy and paste the URL.

https://youtu.be/sYcq2e0-ins

**Comment by gregzaal** [comment] 2018-08-17 10:27
Thanks, it seems like there might be some unsupported characters in your HDRI path - though I can't be sure unless you click [these two buttons](https://i.imgur.com/uWLeT3L.png) and send me the links of the pages it opens.

If I'm right, this is a known limitation (duplicate of issue #64). The workaround is to use only standard english letters in the names of all the folders leading to your HDRIs.

**Comment by FuuChang** [comment] 2018-08-17 13:18
Thank you! Thank you! Thank you very much!
Correcting the folder name as you said it worked perfectly!
Thank you very much for using time for a very primitive problem.
I hope this add-on will be bigger. Thank you very much.

**Closed** 2018-08-17 13:37 UTC
