### ISSUE TITLE
can not use in 3.4+

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [gregzaal/Gaffer#156] opened 2023-02-15 14:11 UTC
cannot use in 3.4+
```
Traceback (most recent call last):
  File "G:\blender\blender35\3.5\scripts\modules\addon_utils.py", line 333, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'

```

**Comment by gregzaal** [comment] 2023-02-15 14:20
Duplicate of #112

**Closed by gregzaal** 2023-02-15 14:20 UTC
