### ISSUE TITLE
broken in 3.1

### ISSUE THREAD

**Issue by BUGProtectionAssociation** [gregzaal/Gaffer#137] opened 2021-12-16 01:55 UTC
Traceback (most recent call last):
  File "G:\blender\blender3.0\3.1\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
ModuleNotFoundError: No module named 'Gaffer-3'

No Gaffer-3

**Comment by gregzaal** [comment] 2021-12-16 17:18
Duplicate of #112

**Closed by gregzaal** 2021-12-16 17:18 UTC
